version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.10.12-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - -m
      - models
      - --enable-api
      - --cors
      - "*"
      - --debug
  app:
    image: ketanp01/customaction:v3
    expose: 
      - 5055
